# Generated by Django 5.2.6 on 2025-09-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='demands',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='label',
            field=models.IntegerField(choices=[(4, 'Speed/Endurance'), (1, 'Strength'), (5, 'Endurance'), (2, 'Strength/Power'), (3, 'Power/Speed')]),
        ),
    ]
