# Generated by Django 5.2.6 on 2025-09-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_type_demands_alter_type_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='label',
            field=models.IntegerField(choices=[(3, 'Power/Speed'), (5, 'Endurance'), (4, 'Speed/Endurance'), (2, 'Strength/Power'), (1, 'Strength')]),
        ),
    ]
