# Generated by Django 5.2.6 on 2025-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_type_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='label',
            field=models.IntegerField(choices=[(4, 'Speed/Endurance'), (3, 'Power/Speed'), (2, 'Strength/Power'), (1, 'Strength'), (5, 'Endurance')]),
        ),
    ]
